### ISSUE TITLE
maj

### ISSUE THREAD

**Issue by ninalem** [ninalem/bookorama#1]
Bon je sais que tu vas avoir envie de hurler x)
Mais honnêtement je vois pas comment entrer les données nécessaires à l'intérieur d'un tableau
Donc j'ai pas fait de tableau et j'ai laissé des variables inutilisables pour qu'on voit ce que je suis supposée rentrer dedans.
J'ai aussi créé une deuxième fonction datas to champ pour mon champs2 (je me souviens que t'as dit qu'il serait pas possible de le mettre... mais là encore je vois pas comment faire sans)

**Comment by olag18** [comment]
mavariable = array()                 ## pour creer un tableau
unestring = 'une string'           ## pour creer une string
untablo = array( 'une clée' => 'une valeur')       ## la reponse a ta question
